
name: CI

on:
  push

#TODO What permission is need here to attach artifact to workflow run: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defining-access-for-the-github_token-scopes
permissions: {}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      
      - name: pester tests
        uses: zyborg/pester-tests-report@bb711b31e93f78f7423086d57f81928325829765 # v1.5.0
        with:
          include_paths: ./tests/GitHubActions_tests.ps1
          exclude_tags: SkipCI
          report_name: action_base_tests
          report_title: Action Base Tests
          gist_name: pwsh-github-action-base_tests.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_badge_label: Tests %ExecutedAt%

      # - name: pester tests manually
      #   shell: pwsh
      #   run: |
      #     $neededModules = @(
      #       'Pester'
      #       'GitHubActions'
      #     )
      #     $neededModules | % {
      #       if (-not (Get-Module -ListAvailable $_)) {
      #         Install-Module $_ -Force
      #       }
      #     }
      #     ./tests/GitHubActions_tests.ps1

      # - name: bundle distributable components
      #   shell: pwsh
      #   run: |
      #     Compress-Archive -DestinationPath ./dist.zip -Path @(
      #       'js',  'lib'
      #       'SAMPLE-*', 'LICENSE', 'README.md'
      #     )

  ## For testing out tests on Windows
  build-on-win:
    runs-on: windows-latest
    permissions:
      checks: write
    continue-on-error: true
    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      
      - name: pester tests
        uses: zyborg/pester-tests-report@bb711b31e93f78f7423086d57f81928325829765 # v1.5.0
        with:
          include_paths: ./tests/GitHubActions_tests.ps1
          exclude_tags: SkipCI
          report_name: action_base_tests-on-win
          report_title: Action Base Tests (On Windows)
          github_token: ${{ secrets.GITHUB_TOKEN }}
